<a href="https://colab.research.google.com/github/meryemtetik/Assignment-1/blob/master/Kopie_von_Stats_Assign_(Central_Tendency%26_Dispersion).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [1]:
import numpy as np
from scipy import stats
import pandas as pd

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [2]:
samples = np.random.normal(100,15,1000)
samples

array([100.56867788, 128.48120272,  93.49215262, 123.86928615,
        57.60890876, 107.09650425,  93.48347337,  97.70405495,
       103.69835649, 124.02439333,  83.56160696, 114.36683353,
       107.31457326,  95.08165134,  95.92403288,  99.63298884,
       114.32363917,  91.42799659,  88.60704133,  59.70476132,
        77.18463107, 115.34699444,  99.03099354, 126.20939875,
       119.71232893,  77.87585873,  86.81261119,  89.49608851,
        76.02001565,  83.11799257,  88.66362329,  93.65089078,
        80.41112769,  68.83608957,  91.22697724,  91.93950132,
       111.33829619,  86.95307995,  92.10372639, 109.38891423,
        85.19346388,  67.4384267 ,  65.00662884,  85.7604036 ,
       113.49928651, 100.800222  , 102.48627738, 128.78337938,
        93.43926877,  94.02974258,  71.6494594 ,  89.95192122,
        97.8050775 , 118.82974079,  96.79044338, 103.64101355,
        93.77732003,  83.71038014, 103.78394206,  96.96189442,
       113.55345203, 106.65769761,  78.7696892 , 112.18

Compute the **mean**, **median**, and **mode**

In [3]:
mean = np.mean(samples)
median =np.median(samples)
mode =stats.mode(samples)
print(mean)
print(median)
print(mode)

98.90616595010475
98.48616760012355
ModeResult(mode=array([53.1421176]), count=array([1]))


Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [4]:
min = np.min(samples)
max = np.max(samples)
q1 = np.percentile(samples, 25)
q3 = np.percentile(samples, 75)
iqr = stats.iqr(samples)    # or   iqr = q3-q1
print(min)
print(max)
print(q1)
print(q3)
print(iqr)

53.14211759608388
151.92136139253392
88.59562739894758
109.30552582379784
20.709898424850252


Compute the **variance** and **standard deviation**

In [5]:
variance = np.var(samples)
std_dev = np.std(samples)
print(variance)
print(std_dev)

233.9436495638488
15.29521655825274


Compute the **skewness** and **kurtosis**

You can use [`scipy.stats.skew`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.skew.html) and [`scipy.stats.kurtosis`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kurtosis.html)

In [6]:
from scipy.stats import kurtosis, skew
from scipy import stats
skewness = skew(samples)    #or   skewness = scipy.stats.skew(samples) ??
kurtosis = kurtosis(samples)    #or kurtosis = scipy.stats.kurstosis(samples) ??
print(skewness)
print(kurtosis)

0.033245828113820125
-0.047631407289335126


## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [7]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [8]:
y = np.array([np.random.randint(0, 100) for i in range(10)])   #??????????
y   #or y = np.array(np.random.randint(0,100,10))

array([88, 67, 16, 87, 14, 72, 48, 31, 69, 41])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [9]:
r = np.corrcoef(x, y)
r

array([[ 1.        , -0.26359145],
       [-0.26359145,  1.        ]])

## Pandas Correlation Calculation

Run the code below

In [10]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [11]:
r = stats.pearsonr(x, y)
r

(0.758640289091187, 0.010964341301680813)

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [12]:
rho = stats.spearmanr(x, y)
rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

## Seaborn Dataset Tips

Import Seaborn Library

In [13]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [14]:
tips = sns.load_dataset("tips")
tips.head

<bound method NDFrame.head of      total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]>

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [15]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [16]:

tips.corr()

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000